env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'

rules:
  {
    "@typescript-eslint/ban-ts-ignore": 0,
    "@typescript-eslint/no-empty-function": 1,
    "@typescript-eslint/member-delimiter-style": 0,
    "@typescript-eslint/explicit-function-return-type": 1,
    "@typescript-eslint/no-unused-vars": 0,
    "@typescript-eslint/strict-boolean-expressions": 0,
  }
